version: '3.8'

networks:
  lab_01:
   
volumes:
  mongo_vol:

services:
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - '8081:8081'
    networks:
      - lab_01
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/
  mongodb:
    image: mongo:4.4.3
    restart: always
    volumes:
      - mongo_vol:/data/db
    networks:
      - lab_01
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}